name: PaulCornwall
favicon: null
layout_spectrum: 0.9274923640768975
typography_spectrum: 0.22958635119721293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.44230530550703406
  lightness: 0.0522022123914212
  saturation: 0.9797324652317911
  rhythmicContrast: 0.45764237828552723
purpose: []
